Repository brazil-data-cube/bdc-auth-client, pull requests merged in 2020-08, with the labels that each got.

#6 add required variable if not necessary token in decorator
  bdc_auth_client/decorators.py
Labels: enhancement

#7 return access_token in decorator
  bdc_auth_client/decorators.py
Labels: enhancement

#8 accept token in header (x-api-key)
  bdc_auth_client/decorators.py
Labels: enhancement

#15 fix save roles in cache (add empty list and not 'None')
  bdc_auth_client/decorators.py
Labels: bug

#17 Release Version 0.2.1
  CHANGES.rst
  bdc_auth_client/version.py
Labels: release
